apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: php
spec:
  selector:
    app: my-php-backend
  ports:
  - protocol: TCP
    port: 2545
    targetPort: http-web-svc
  type: NodePort
