apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-php-backend-deployment
  namespace: php
  labels:
    app: my-php-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-php-backend
  template:
    metadata:
      labels:
        app: my-php-backend
    spec:
      containers:
      - name: my-php-backend
        image: fahdinov/my-php-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http-web-svc
        env:
        - name: MARIADB_HOST
          value: "mariadb.mariadb.svc.cluster.local"
        - name: MARIADB_ROOT_USER
          value: "root"
        - name: MARIADB_ROOT_PASSWORD
          value: "root"
        - name: MARIADB_DATABASE
          value: "phpdb"